# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data.proto',
  package='test',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ndata.proto\x12\x04test\"+\n\x1bTestClientSendStreamRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\".\n\x1cTestClientSendStreamResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2s\n\x0eTestClientSend\x12\x61\n\x14TestClientSendStream\x12!.test.TestClientSendStreamRequest\x1a\".test.TestClientSendStreamResponse\"\x00(\x01\x62\x06proto3'
)




_TESTCLIENTSENDSTREAMREQUEST = _descriptor.Descriptor(
  name='TestClientSendStreamRequest',
  full_name='test.TestClientSendStreamRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='test.TestClientSendStreamRequest.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=63,
)


_TESTCLIENTSENDSTREAMRESPONSE = _descriptor.Descriptor(
  name='TestClientSendStreamResponse',
  full_name='test.TestClientSendStreamResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='test.TestClientSendStreamResponse.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=111,
)

DESCRIPTOR.message_types_by_name['TestClientSendStreamRequest'] = _TESTCLIENTSENDSTREAMREQUEST
DESCRIPTOR.message_types_by_name['TestClientSendStreamResponse'] = _TESTCLIENTSENDSTREAMRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TestClientSendStreamRequest = _reflection.GeneratedProtocolMessageType('TestClientSendStreamRequest', (_message.Message,), {
  'DESCRIPTOR' : _TESTCLIENTSENDSTREAMREQUEST,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:test.TestClientSendStreamRequest)
  })
_sym_db.RegisterMessage(TestClientSendStreamRequest)

TestClientSendStreamResponse = _reflection.GeneratedProtocolMessageType('TestClientSendStreamResponse', (_message.Message,), {
  'DESCRIPTOR' : _TESTCLIENTSENDSTREAMRESPONSE,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:test.TestClientSendStreamResponse)
  })
_sym_db.RegisterMessage(TestClientSendStreamResponse)



_TESTCLIENTSEND = _descriptor.ServiceDescriptor(
  name='TestClientSend',
  full_name='test.TestClientSend',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=113,
  serialized_end=228,
  methods=[
  _descriptor.MethodDescriptor(
    name='TestClientSendStream',
    full_name='test.TestClientSend.TestClientSendStream',
    index=0,
    containing_service=None,
    input_type=_TESTCLIENTSENDSTREAMREQUEST,
    output_type=_TESTCLIENTSENDSTREAMRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TESTCLIENTSEND)

DESCRIPTOR.services_by_name['TestClientSend'] = _TESTCLIENTSEND

# @@protoc_insertion_point(module_scope)
